plugins {
    id 'java'
    id 'jacoco'
}

group = 'ru.java.mifi.demo'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.testng:testng:7.1.0'
    implementation 'com.microsoft.playwright:playwright:1.56.0'
}

test {
    useTestNG()
    finalizedBy jacocoTestReport // Ensure report generation after tests
}

jacoco {
    toolVersion = "0.8.11" // Specify the JaCoCo tool version
}

jacocoTestReport {
    reports {
        html.required = true // Enable HTML report
    }
    // Customize destination directories if needed
    // reports.html.outputLocation = layout.buildDirectory.dir("jacocoHtml")
}
